version: "3.9"
services: 
 database:
  build: ./mysql
  ports:
   - 5432:3306
 app:
  build: ./web-app
  ports:
   - 5500:5500
  depends_on:
   - database
 updator:
  build: ./db_updator
  depends_on:
   - database