HOST = "localhost" #INTRODUZCA SU HOST
USER = "root" #INTRODUZCA SU USUARIO. DEBE TENER PERMISOS PARA SELECT; INSERT; UPDATE Y DELETE
PASSWORD = "PutosRusosSQL13186" #INTRODUZCA SU CONTRASEÑA
DATABASE = "TFM_DB2" #INTRODUZCA SU CONTRASEÑA
TIME_IN_BETWEEN_SEARCH = 30 #TIEMPO QUE TRASCURRE ENTRE LLAMADAS A GETTRYTES A PARTIR DE HASHES