---
- name: installing pip3
  apt: 
    name: python3-pip
    state: present
- name: install virtualenv
  pip:
    name: virtualenv
- name: Install specified python requirements in indicated (virtualenv)
  pip:
    requirements: "/usr/src/TFM13186/{{ endpoint }}" #PATH C
    virtualenv: "{{ path }}/TFM13186" #PATH C
    virtualenv_python: