---
- name: installing pip3
  apt: 
    name: python3-pip
    state: present
- name: install virtualenv
  pip:
    name: virtualenv
- name: Install specified python requirements in indicated (virtualenv)
  pip:
    requirements: "{{ path }}/{{ endpoint }}" #PATH C
    virtualenv: "{{ path }}/TFM13186" #PATH C
    virtualenv_python:
- name: Install python chrysalis lib in indicated (virtualenv)
  pip:
    name: "{{ path }}/{{ lib }}" #PATH C
    virtualenv: "{{ path }}/TFM13186" #PATH C
    virtualenv_python:    